---
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Python dependencies
        run: |
          pip install tox
      - name: Test with tox
        run: |
          tox -e check-prod

name: check

# We want to run this workflow every time we build the site.
# In addition, we want to run it once a week on a schedule.
'on':
  schedule:
    - cron: '0 12 * * 3'
  workflow_dispatch:
