---
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Python dependencies
        run: |
          pip install tox
      - name: Deploy to gh-pages
        run: tox -e deploy-github

name: deploy

'on':
  push:
    branches:
      - main
